# @format

version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    command:
      bash -c "python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
